### ISSUE TITLE
Update to Node.js 16

### ISSUE THREAD

**Issue by wooyek** [aschbacd/gitlint-action#14]
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: aschbacd/gitlint-action@v1.1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by zhu0629** [comment]
@aschbacd

**Comment by aschbacd** [comment]
Hi, sorry it took so long. Updated nodejs to v20 now.
